### ISSUE TITLE
数据集无法读取

### ISSUE THREAD

**Issue by stakeswky** [dbbbbm/UAE#1]
你好，我下载了你所提供的数据集，但是无法正常读取数据

**Comment by dbbbbm** [comment]
不好意思，目前读数据这部分还没有完善。目前只能先运行xray_data.py这个文件将数据集中的normal, not normal 和 lung opacity三类分到三个文件夹中，然后手动划分训练和测试集到数据目录下的train（只有normal类）和test（normal vs lung opacity或者normal vs not normal）文件夹中。对您造成了困扰我很抱歉。

**Comment by stakeswky** [comment]
我按你说的，将normal类中的若干图放入了train文件夹中，但程序仍然无法读取到数据。然后还有一个就是uae_main.py在运行是会报Segmentation fault的错误，但我没能debug出是哪里的问题

**Comment by dbbbbm** [comment]
把normal类中的若干图放到train/0或test/0目录下，异常的放入test/1目录下

**Comment by stakeswky** [comment]
可以了，谢谢
